name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ECR_REPO: ${{ secrets.ECR_REPO }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
          docker login --username AWS --password-stdin $ECR_REPO

      - name: Build Docker Image
        run: |
          docker build -t my-app .
          docker tag my-app:latest $ECR_REPO:latest

      - name: Push Docker Image to ECR
        run: |
          docker push $ECR_REPO:latest

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Add deployment scripts here, e.g., Kubernetes manifests or other infra management tools

      - name: Test APIs
        run: |
          echo "Testing Pinecone and OpenAI APIs..."
          curl -H "Authorization: Bearer $PINECONE_API_KEY" https://api.pinecone.io/v1
          curl -H "Authorization: Bearer $OPENAI_API_KEY" https://api.openai.com/v1

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up resources..."
